### ISSUE TITLE
Fails to initialize due to ImportError trying to import `identify_database`

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian-auth#2]
Using @b963fd40

```
ERROR:root:Component librarian_auth encountered an error during it's loading, installation skipped.
Traceback (most recent call last):
  File "/home/hajime/code/librarian-core/librarian_core/dependencies.py", line 64, in _import_modules
    mod = importlib.import_module(mod_path)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/hajime/code/librarian-auth/librarian_auth/plugins.py", line 5, in <module>
  File "/home/hajime/code/librarian-auth/librarian_auth/users.py", line 22, in <module>
  File "/home/hajime/code/librarian-auth/librarian_auth/groups.py", line 3, in <module>
ImportError: cannot import name identify_database
```

**Comment by foxbunny** [comment]
pyc plague. :(
